package com.niw.ecomm.domain;

import java.util.ArrayList;
import java.util.List;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Represents a customer of the online store.
 *
 * <p>
 * Owns a collection of {@link Order} instances through a bidirectional
 * one-to-many relationship. Cascade operations and orphan removal are delegated
 * to JPA.
 */
@Entity
@Table(name = "customers")
public class Customer {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  @Column(nullable = false, length = 100)
  private String name;

  @Column(nullable = false, length = 100)
  private String email;

  @OneToMany(mappedBy = "customer", cascade = CascadeType.ALL, orphanRemoval = true)
  private List<Order> orders = new ArrayList<>();

  /** Required by JPA. */
  protected Customer() {
  }

  /**
   * Test-friendly constructor — allows setting a known id without JPA
   * persistence.
   *
   * @param id    the id to assign
   * @param name  the customer's full name
   * @param email the customer's email address
   */
  public Customer(Long id, String name, String email) {
    this.id = id;
    this.name = name;
    this.email = email;
  }

  /**
   * Creates a new customer without a pre-assigned id. The id will be generated by
   * the database upon persistence.
   *
   * @param name  the customer's full name
   * @param email the customer's email address
   */
  public Customer(String name, String email) {
    this.name = name;
    this.email = email;
  }

  /**
   * Returns the unique identifier of this customer.
   *
   * @return the database-generated id, or {@code null} before first persistence
   */
  public Long getId() {
    return id;
  }

  /**
   * Returns the customer's full name.
   *
   * @return name
   */
  public String getName() {
    return name;
  }

  /**
   * Returns the customer's email address.
   *
   * @return email
   */
  public String getEmail() {
    return email;
  }

  /**
   * Returns the list of orders placed by this customer.
   *
   * @return mutable list of orders; never {@code null}
   */
  public List<Order> getOrders() {
    return orders;
  }
}
